# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CJ-Delivery-App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CJ-Delivery-App
  pod 'SnapKit'
end
